name: Publish to pub.dev

on:
  push:
    tags:
    # Must align with the tag-pattern configured on pub.dev.
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Allows to publish to pub.dev without personal credentials

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.1.1
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
          
      - name: Publish Dart/Flutter package
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          skip_test: true
